### ISSUE TITLE
Practica 3 interfaz grafica 

### ISSUE THREAD

**Issue by AmilkarVladimiR** [SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-michingenierode-sistemas-1#1]
[Practica 3 Prototipo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-de-interfaz-grafica-con-interactividad-michingenierode-sistemas-1/files/10762940/Practica.3.Prototipo.pdf)

**Comment by JoseMVasquezD** [comment]
Un buen trabajo con una calificación de 84
Porcentaje=16.8%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
